# Generated by Django 4.2 on 2023-06-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='rating',
            new_name='Rateing',
        ),
        migrations.RenameField(
            model_name='plane',
            old_name='reviewer',
            new_name='Reviewer',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='descripton',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='name',
        ),
        migrations.AddField(
            model_name='plane',
            name='Cost',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plane',
            name='Manufacturer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='plane',
            name='Speed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plane',
            name='Year_Published',
            field=models.TextField(default=''),
        ),
    ]
