# Generated by Django 4.2 on 2023-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_rename_rating_plane_rateing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='Cost',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='plane',
            name='Speed',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='plane',
            name='Year_Published',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
