# Generated by Django 4.2 on 2023-06-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_alter_plane_cost_alter_plane_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
