# Generated by Django 4.2 on 2023-06-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0004_plane_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='Rateing',
        ),
    ]
